# Generated by Django 3.2.14 on 2022-12-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_auto_20221229_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='updated_at',
        ),
    ]
