# Generated by Django 3.2.14 on 2023-01-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0009_alter_event_end_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_day',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_day',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
