# Generated by Django 3.2.14 on 2023-01-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0010_auto_20230102_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
    ]
