# Generated by Django 3.2.14 on 2023-01-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0011_alter_event_all_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='notes',
            new_name='post_comments',
        ),
        migrations.AddField(
            model_name='event',
            name='post_exertion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='post_fb_neg',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='post_fb_pos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='post_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
