# Generated by Django 3.2.14 on 2023-01-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0012_auto_20230103_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_post',
            field=models.BooleanField(default=False),
        ),
    ]
