# Generated by Django 3.2.14 on 2023-01-06 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0013_event_is_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='calendarapp.eventcategory'),
        ),
    ]
