# Generated by Django 3.2.14 on 2023-01-06 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0014_eventcategory_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='calendarapp.eventcategory'),
        ),
    ]
