# Generated by Django 3.2.14 on 2023-01-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0015_alter_eventcategory_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='planned_exertion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
