# Generated by Django 4.1.5 on 2024-04-27 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0016_event_planned_exertion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcategory",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="calendarapp.eventcategory",
            ),
        ),
    ]
