# Generated by Django 4.1.5 on 2024-04-27 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0018_exercise"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="category",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="user",
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="calendarapp.eventcategory",
            ),
        ),
    ]
