# Generated by Django 4.1.5 on 2024-04-27 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0020_exercise_duration_exercise_reps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="title",
        ),
        migrations.CreateModel(
            name="ExerciseCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories",
                        to="calendarapp.exercisecategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exercise",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="calendarapp.exercisecategory",
            ),
        ),
    ]
