# Generated by Django 4.1.5 on 2024-04-27 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0021_remove_exercise_title_exercisecategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercisecategory",
            name="category",
        ),
        migrations.AlterField(
            model_name="exercise",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="calendarapp.exercisecategory",
            ),
        ),
    ]
