# Generated by Django 4.1.5 on 2024-05-02 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0022_remove_exercisecategory_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["created_at"]},
        ),
    ]
