# Generated by Django 4.1.5 on 2024-05-02 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0024_alter_event_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="event",
            field=models.ForeignKey(
                limit_choices_to={"is_deleted": False},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="calendarapp.event",
            ),
        ),
    ]
