# Generated by Django 4.1.5 on 2024-05-03 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0025_alter_exercise_event"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-start_datetime"]},
        ),
    ]
